=== hmcts/cpp-context-prosecution-casefile-dlrm/pcfdlrm-command/pcfdlrm-command-api/src/raml/json/schema/pcfdlrm.receive-migrated-case-file.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://moj.gov.uk/cps/pcfdlrm/command/api/receive-migrated-case-file.json",
  "type": "object",
  "description": "Migrated Case File Receive",
  "properties": {
    "migratedCaseDetails": {
      "$ref": "http://cpp.moj.gov.uk/prosecution/casefile/dlrm/migrated/json/schemas/migrated-case-details.json"
    },
    "materials": {
      "type": "array",
      "items": {
        "$ref": "http://cpp.moj.gov.uk/prosecution/casefile/dlrm/migrated/json/schemas/migrated-material.json"
      }
    },
    "channel": {
      "type": "string",
      "$ref": "http://cpp.moj.gov.uk/prosecution/casefile/dlrm/json/schemas/pcf-definitions.json#/definitions/channel"
    },
    "submissionId": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    }
  },
  "required": [
    "migratedCaseDetails",
    "submissionId"
  ],
  "additionalProperties": false
}

=== hmcts/cpp-context-prosecution-casefile-dlrm/pcfdlrm-command/pcfdlrm-command-api/src/raml/json/pcfdlrm.receive-migrated-case-file.json
{
  "migratedCaseDetails": {
    "caseDetails": {
      "originatingOrganisation": "cps",
      "summonsCode": "summonsCode",
      "caseId": "51cac7fb-387c-4d19-9c80-8963fa8cf222",
      "initiationCode": "H",
      "prosecutorCaseReference": "TVL55117DFXXV",
      "prosecutor": {
        "prosecutingAuthority": "GAEAA01",
        "informant": "Adam"
      }
    },
    "defendants": [
      {
        "documentationLanguage": "W",
        "hearingLanguage": "W",
        "individual": {
          "personalInformation": {
            "title": "Baron",
            "firstName": "John",
            "lastName": "Smith",
            "address": {
              "address1": "armagaddon house",
              "postcode": "M60 1NW"
            },
            "contactDetails": {}
          },
          "selfDefinedInformation": {
            "ethnicity": "white",
            "gender": "MALE"
          }
        },
        "initialHearing": {
          "courtHearingLocation": "abcd",
          "dateOfHearing": "02-04-1978",
          "timeOfHearing": "9:05",
          "roomId": "af510310-b85f-4a4e-b0b3-9a4ae4cc9cb1",
          "roomName": "Hill East",
          "hearingListingDirection": "Special Need required",
          "hearingDuration": 60,
          "hearingLanguage": "W"
        },
        "offences": [
          {
            "offenceCode": "CA03013",
            "offenceSequenceNumber": 1,
            "offenceCommittedDate": "2018-09-10",
            "offenceDateCode": 1,
            "offenceLocation": "Croydon",
            "offenceWording": "TV Licence not paid",
            "chargeDate": "2015-04-04",
            "laidDate": "2015-04-04",
            "appliedCompensation": 200
          }
        ],
        "postingDate": "2018-09-10"
      },
      {
        "documentationLanguage": "W",
        "hearingLanguage": "W",
        "individual": {
          "personalInformation": {
            "title": "Baron",
            "firstName": "John",
            "lastName": "Smith",
            "address": {
              "address1": "armagaddon house",
              "postcode": "M60 1NW"
            },
            "contactDetails": {}
          },
          "selfDefinedInformation": {
            "ethnicity": "white",
            "gender": "MALE"
          }
        },
        "offences": [
          {
            "offenceCode": "DA03014",
            "offenceSequenceNumber": 1,
            "offenceCommittedDate": "2018-09-10",
            "offenceDateCode": 1,
            "offenceLocation": "Croydon",
            "offenceWording": "TV Licence not paid",
            "chargeDate": "2015-04-04",
            "appliedCompensation": 200
          }
        ],
        "postingDate": "2018-09-10"
      }
    ],
    "migrationSourceSystem": {
      "migrationSourceSystemName": "LIBRA",
      "migrationSourceSystemCaseIdentifier": "This is from Libra"
    }
  },
  "materials": [
    {
      "id": "550e8400-e29b-41d4-a716-446655440001",
      "azureLocation": "http://inazure/secrets/1",
      "fileName": "Audio Recording one",
      "fileType": ".wav",
      "documentType": 3
    },
    {
      "id": "550e8400-e29b-41d4-a716-446655440000",
      "azureLocation": "http://inazure/secrets/2",
      "fileName": "Audio Recording two",
      "fileType": ".wav",
      "documentType": 3
    }
  ],
  "channel": "DLRM_MIGRATION",
  "submissionId": "550e8400-e29b-41d4-a716-446655440000"
}
